# Generated by Django 5.0.4 on 2024-07-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="User",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="scheduler.user",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider",
                to="scheduler.user",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer",
                to="scheduler.user",
            ),
        ),
    ]
